/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReklamaRouteImport } from './routes/reklama'
import { Route as RealicoXRouteImport } from './routes/realico-x'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as BiznisSRealicoRouteImport } from './routes/biznis-s-realico'
import { Route as IndexRouteImport } from './routes/index'

const ReklamaRoute = ReklamaRouteImport.update({
  id: '/reklama',
  path: '/reklama',
  getParentRoute: () => rootRouteImport,
} as any)
const RealicoXRoute = RealicoXRouteImport.update({
  id: '/realico-x',
  path: '/realico-x',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const BiznisSRealicoRoute = BiznisSRealicoRouteImport.update({
  id: '/biznis-s-realico',
  path: '/biznis-s-realico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biznis-s-realico': typeof BiznisSRealicoRoute
  '/kontakt': typeof KontaktRoute
  '/realico-x': typeof RealicoXRoute
  '/reklama': typeof ReklamaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biznis-s-realico': typeof BiznisSRealicoRoute
  '/kontakt': typeof KontaktRoute
  '/realico-x': typeof RealicoXRoute
  '/reklama': typeof ReklamaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biznis-s-realico': typeof BiznisSRealicoRoute
  '/kontakt': typeof KontaktRoute
  '/realico-x': typeof RealicoXRoute
  '/reklama': typeof ReklamaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biznis-s-realico' | '/kontakt' | '/realico-x' | '/reklama'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biznis-s-realico' | '/kontakt' | '/realico-x' | '/reklama'
  id:
    | '__root__'
    | '/'
    | '/biznis-s-realico'
    | '/kontakt'
    | '/realico-x'
    | '/reklama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiznisSRealicoRoute: typeof BiznisSRealicoRoute
  KontaktRoute: typeof KontaktRoute
  RealicoXRoute: typeof RealicoXRoute
  ReklamaRoute: typeof ReklamaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reklama': {
      id: '/reklama'
      path: '/reklama'
      fullPath: '/reklama'
      preLoaderRoute: typeof ReklamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realico-x': {
      id: '/realico-x'
      path: '/realico-x'
      fullPath: '/realico-x'
      preLoaderRoute: typeof RealicoXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biznis-s-realico': {
      id: '/biznis-s-realico'
      path: '/biznis-s-realico'
      fullPath: '/biznis-s-realico'
      preLoaderRoute: typeof BiznisSRealicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiznisSRealicoRoute: BiznisSRealicoRoute,
  KontaktRoute: KontaktRoute,
  RealicoXRoute: RealicoXRoute,
  ReklamaRoute: ReklamaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
